### ISSUE TITLE
sanitize variable names for target output

### ISSUE THREAD

**Issue by hipstersmoothie** [marcomontalbano/figma-export#102]
I am trying to output my tokens into css variables but the token names are not valid variable names

ex:

```css
--Grey/900: rgba(26, 26, 26, 1);
```

I'd either want the ability to customize how the names are created or just have the tool output a usable name

**Comment by marcomontalbano** [comment]
Thanks @hipstersmoothie for noticing this issue. I'll work on this :+1:

**Comment by marcomontalbano** [comment]
Hi @hipstersmoothie, this fix has been added to version `v4.0.0` 🚀 

I also added a `getVariableName` options to all style-outputters, so that you can customize the way you generate the variable name.
