### ISSUE TITLE
SVGR additional options (index.js)

### ISSUE THREAD

**Issue by inspiratweb** [marcomontalbano/figma-export#112]
Hi! I was testing the current SVGR outputter but I miss some extra configuration.

My suggestions:
- When creating components in .tsx (getFileExtension) index file should be `index.ts`, not `index.js`
- Add an option to customize exports from that index.ts `export { default as ${reactComponentName} } from './${basename}';`

I've created a fork for this, if you think this could be useful I can create a PR here

Thanks!

**Comment by marcomontalbano** [comment]
Good catch @inspiratweb , if you already have a working proposal, please create the PR so that I can check.
I think that both are good ideas.

**Comment by inspiratweb** [comment]
Hi! proposal updated here: https://github.com/marcomontalbano/figma-export/pull/114

Ping me if you need something else, please.

**Comment by marcomontalbano** [comment]
Hi @inspiratweb, thanks a lot for the time you spent on this! I just released version [`v4.2.0`](https://github.com/marcomontalbano/figma-export/releases/tag/v4.2.0) which contains this new feature.
Let me know if everything work properly!

**Comment by inspiratweb** [comment]
Hi @marcomontalbano, everything is working perfectly in 4.2.0, thank you!
