### ISSUE TITLE
Export styles from page or node

### ISSUE THREAD

**Issue by Nemhis** [marcomontalbano/figma-export#118]
Hello.
First i wanna thank you for great figma export module, it`s really cool!

I need to export styles from specific page of figma to keep the best structure of our design system in figma. `Figma-js` accepts `ids` params to get only certain nodes, it seems that's what I need. 
![image](https://user-images.githubusercontent.com/26406885/164558390-6e501a37-2100-428b-a7b5-557c821823cf.png)

But `@figma-export/output-styles-as-sass` doesn`t accept ids. it would be nice to be able to load only certain nodes.

**Comment by marcomontalbano** [comment]
Hi @Nemhis, glad to hear you appreciation !!

At the moment with Figma Export there's the option `onlyFromPages` to export only specific pages:

```diff
[
    ['components', {
        fileId: 'fzYhvQpqwhZDUImRz431Qo',
+       onlyFromPages: ['icons'],
        outputters: [
            require('@figma-export/output-styles-as-sass')({
                output: './output/styles'
            })
        ]
    }]
]
```

Let me know if this is what you were looking for.

**Comment by Nemhis** [comment]
Now we have this pages for web designers. 
![image](https://user-images.githubusercontent.com/26406885/166684330-c34998a8-ac5f-486a-9e56-ae6405ed26f5.png)

This figma pages structure is convenient for designers and developers.
Whith export styles from specific pages we can organize our export like 
```js
require('dotenv').config()

const fileId = 'your_file_id';

module.exports = {
  commands: [
    ['styles', {
      fileId,
      onlyFromPages: ['Colors'],
      outputters: [
        require('@figma-export/output-styles-as-sass')({
          output: './tokens',
          getFilename: () => 'colors',
        })
      ]
    }],

    ['styles', {
      fileId,
      onlyFromPages: ['Typography'],
      outputters: [
        require('@figma-export/output-styles-as-sass')({
          output: './tokens',
          getFilename: () => 'typography',
        })
      ]
    }],

    ['styles', {
      fileId,
      onlyFromPages: ['Corners'],
      outputters: [
        require('@figma-export/output-styles-as-sass')({
          output: './tokens',
          getFilename: () => 'corners',
        })
      ]
    }],
  ],
};
```

![image](https://user-images.githubusercontent.com/26406885/166685806-5112431c-0851-474a-bc58-a0223c2e48e1.png)

**Comment by Nemhis** [comment]
And i wanna ask one more question about scss export:
How to export shadows ? result of shadow export look like 
```scss
$-1dp: inset 0px 2px 8px 0px rgba(63, 64, 69, 0.12);

/**
 * Elements
 */
$1dp: 0px 6px 8px 0px rgba(63, 64, 69, 0.12);

/**
 * Cards
 */
$2dp: 0px 12px 16px 0px rgba(63, 64, 69, 0.12);

/**
 * Modals
 */
$3dp: 0px 18px 32px 0px rgba(63, 64, 69, 0.12);
```

Digits in var name is wrong scss syntax

**Comment by marcomontalbano** [comment]
Hi @Nemhis,
the export options between `styles` and `components` are different. For example, when you export styles you don't have the `onlyFromPages` option.

Looking at the configuration you shared above, I don't think that is working as you would like. I'm expecting that all of your three file will have the same content. Am I right?

As I said in my previous comment, `styles`, in Figma, are set at file level and not at page level because they are shared across all the pages within a file.

---

About the syntax error in scss, there's no validation on that. The method that generates the variable name is called `getVariableName` and you can override the default one as you prefer:

```diff
require('@figma-export/output-styles-as-sass')({
    output: './output',
    getExtension: () => 'SCSS',
    getFilename: () => '_variables',
+   getVariableName: (style) => kebabCase(style.name).toLowerCase(),
})
```

`style.name` is exactly that name that you gave to your style. So if you named it `2dp` that style will be exported exactly with that variable name.
This is because I don't want to manipulate too much the information that I get from Figma.

I suggest you to put a prefix in the style name, for example `modal-3dp` .. this could be enought.

You can use digits in var names, but the var name cannot start with a digit.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1681269/166821362-51a78f4f-da68-423f-9e0e-0e7c532efd4e.png">

**Comment by Nemhis** [comment]
You're really right, the page name can only be specified when exporting components, but not styles. But for styles, we can still use the [node id](https://www.figma.com/plugin-docs/api/properties/nodes-id/).
Node id in url:
```
https://www.figma.com/file/FILE_ID/?version-id=VERSION&node-id=NODE_ID
```

I made a "dirty" sample code to demonstrate a working export scheme from different Figma nodes - [PR](https://github.com/marcomontalbano/figma-export/pull/119).

----

Another way is to add the ability to configure the export for each style. For example:
```js
require('dotenv').config()
const outputAsSass = require('@figma-export/output-styles-as-sass');

const StyleTypes = {
  EFFECT: 'EFFECT',
  FILL: 'FILL',
  TEXT: 'TEXT',
}

const getFilename = (style) => {
  switch (style.styleType) {
    case StyleTypes.EFFECT:
      return '_effects'
    case StyleTypes.FILL:
      return '_colors'
    case StyleTypes.TEXT:
      return '_typography'
  }
}

module.exports = {
  commands: [
    ['styles', {
      fileId: "your_file_id",
      outputters: [
        outputAsSass((style) => {
          // Here we can customize the style for exporting in our own way
          return {
            output: './tokens',
            fileName: getFilename(style),
            // and other configs
          }
        })
      ]
    }],
  ]
};


```

**Comment by marcomontalbano** [comment]
Hi @Nemhis, exporting styles using ids is something that I didn't know. That's interesting.
At this point I think that I could add the same `onlyFromPages` also for styles to keep consistency between the two export.
What do you think about? This should solve you issue.

Thanks for the suggestion :smile:

**Comment by Nemhis** [comment]
@marcomontalbano that would be great, thank you

**Comment by marcomontalbano** [comment]
Hi @Nemhis, I just released [v4.4.0](https://github.com/marcomontalbano/figma-export/releases/tag/v4.4.0). Now you can use `onlyFromPages` also when exporting styles.

**Comment by Nemhis** [comment]
Hi @marcomontalbano , does it work by the page name? wow... thank you very much. It really helps me

**Comment by marcomontalbano** [comment]
Yes it should! Let me know for any issue with that!
