### ISSUE TITLE
feature request: separate out component name and component file name

### ISSUE THREAD

**Issue by wuweiweiwu** [marcomontalbano/figma-export#121]
for `'@figma-export/output-components-as-svgr'` 

the option `getComponentName` also is set as the component file name

in our use case, i would like the file name to be `kebab-case` but the component name to still be `pascal-case` but that is not currently supported.  I can set the `getComponentName` to return the `kebab-case` component names but that is not valid javascript component names

perhaps we can add an option that is `getComponentFileName`

**Comment by marcomontalbano** [comment]
Hi @wuweiweiwu I think that this is a good idea. Thanks for the suggestion. This feature will be part of the next release!

**Comment by marcomontalbano** [comment]
Hi @wuweiweiwu, I just released [v4.4.0](https://github.com/marcomontalbano/figma-export/releases/tag/v4.4.0) with this new `getComponentFilename` property!
