### ISSUE TITLE
Config file option to not include React

### ISSUE THREAD

**Issue by Chusynuk** [marcomontalbano/figma-export#124]
Would be nice to have an option in my config file where I can define if I want to import React or which parts of it, since `Babel` already takes care of it with the `"runtime": "automatic"` option

<img width="319" alt="image" src="https://user-images.githubusercontent.com/4323435/170280942-c94f0515-533d-414f-ab51-6fbb2cffa74c.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/4323435/170282397-5c268798-d6e2-4a3c-8239-5bb49b909e11.png">

_.babelrc_ 

 ```
 "presets": [
    [
      "@nrwl/react/babel", {
        "runtime": "automatic",
        "useBuiltIns": "usage"
      }
    ]
  ],
```

[DOCS](https://dev.to/wojtekmaj/how-to-enable-automatic-runtime-in-react-17-with-babel-preset-react-52l)

**Comment by marcomontalbano** [comment]
Hi @Chusynuk, I think you are referring to `output-components-as-svgr` library, am I right?
This library is a wrapper for [react-svgr](https://react-svgr.com/), you can use the `getSvgrConfig ` option to set a custom [SVGR configuration](https://react-svgr.com/docs/options/) object.
The option that you are looking for is [`jsxRuntime`](https://react-svgr.com/docs/options/#jsx-runtime).

```diff
require('@figma-export/output-components-as-svgr')({
    output: './output',
+   getSvgrConfig: () => ({
+       jsxRuntime: 'automatic'
+   })
})
```

Let me know if this is what you were looking for.

**Comment by Chusynuk** [comment]
> Hi @Chusynuk, I think you are referring to `output-components-as-svgr` library, am I right? This library is a wrapper for [react-svgr](https://react-svgr.com/), you can use the `getSvgrConfig ` option to set a custom [SVGR configuration](https://react-svgr.com/docs/options/) object. The option that you are looking for is [`jsxRuntime`](https://react-svgr.com/docs/options/#jsx-runtime).
> 
> ```diff
> require('@figma-export/output-components-as-svgr')({
>     output: './output',
> +   getSvgrConfig: () => ({
> +       jsxRuntime: 'automatic'
> +   })
> })
> ```
> 
> Let me know if this is what you were looking for.

YEAH! That's exactly what I was looking for 💪  Thanks! @marcomontalbano 

Also thanks for creating and maintaining this library it makes export `Figma` icons a piece of cake 🙌
