### ISSUE TITLE
Drop Node.js 12 and 14 support

### ISSUE THREAD

**Issue by marcomontalbano** [marcomontalbano/figma-export#135]
Drop [Node.js](https://nodejs.org/en/about/releases/) 12 and 14 support starting from figma-export `v5.0.0`.
This will ensure a massive update to the latest dependencies and remove all vulnerability issues.

**Comment by Charlie-Crowdstrike** [comment]
+1

This will also open the path to upgrade the `svgo: ~2.8.0` dependency in `transform-svg-with-svgo` package: https://github.com/marcomontalbano/figma-export/blob/main/packages/transform-svg-with-svgo/package.json#L29

`svgo~2.8.0` carries in its dependency chain an older `css-what` with security vulnerabilities: https://security.snyk.io/package/npm/css-what
