### ISSUE TITLE
Support for require in es6 modules

### ISSUE THREAD

**Issue by EvanSays** [marcomontalbano/figma-export#136]
Hi @marcomontalbano,

Great work! Excited to try out the package. While using the .figmaexportrc.ts file in my "type": "module" project, i came across this error

`
  const err = new Error(getErrRequireEsmMessage(filename, parentPath, packageJsonPath))
              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/Tacos/ui/.figmaexportrc.ts
require() of ES modules is not supported.
require() of /Users/Tacos/ui/.figmaexportrc.ts from /Users/Tacos/ui/node_modules/@figma-export/cli/dist/commands/use-config.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/Tacos/ui/package.json.`

Curious if you know a way around using both require and import inside a es6 project? Perhaps this could [work](https://www.kindacode.com/article/node-js-how-to-use-import-and-require-in-the-same-file/).

**Comment by marcomontalbano** [comment]
Hi @EvanSays, good catch!
How did you solve this?
In the documentation I don't mention it, but I just tried by renaming the configuration file to `.figmaexportrc.cts` and it worked without any other changes.
Let me know so that I can update the documentation, thanks!

**Comment by marcomontalbano** [comment]
I updated the README.md.
Feel free to add a comment here if something is wrong.
