### ISSUE TITLE
onlyFromPages has no effect when exporting styles

### ISSUE THREAD

**Issue by Ingramz** [marcomontalbano/figma-export#147]
Currently when using `onlyFromPages` to export styles, it makes no difference to output whether it is specified or not.

What happens is that the result of `getPages` is always empty because it only returns page nodes that have at least one component associated with them. `client.file` request with depth of 1 does not return any child nodes for a page:

https://github.com/marcomontalbano/figma-export/blob/d62a79bd527a0852323837c3381f37956c231e0f/packages/core/src/lib/export-styles.ts#L28-L29

https://github.com/marcomontalbano/figma-export/blob/d62a79bd527a0852323837c3381f37956c231e0f/packages/core/src/lib/figma.ts#L72

At first I thought that it is sufficient to increase the depth of the initial file request by one to fetch the next level of nodes but eventually realized that the test will still fail when there are no components at the top level of page (for example when using it with `octicons-by-github` page from the demo file).

Removing depth from the file request will work around that limitation, but then another question arises - is it valid to restrict styles to be exported only from pages if they contain at least one component? **Is there any particular reason as to why exporting styles requires a component to be present at the moment?**

---

PS: My goal is to enable exporting both components and styles from hierarchies that may be sub-sections of a page (eg a sub-node with all of its children) which should be a more general case of how onlyFromPages is supposed to work.

**Comment by marcomontalbano** [comment]
Hi @Ingramz, thanks for spotting this out, and sorry for the long wait.

I think that the change you mentioned introduced a regression. I am referring to this one:

https://github.com/marcomontalbano/figma-export/blob/d62a79bd527a0852323837c3381f37956c231e0f/packages/core/src/lib/figma.ts#L72

That change was introduced to avoid exporting empty files (e.g. empty javascript files when exporting components). Probably it was the wrong place to apply that change. I'll do a bit of refactoring and fix this regression.

**Comment by darktasevski** [comment]
This is still an issue. I have a Figma page for the color palette containing only layout nodes and no components. What is the recommendation for handling a scenario like this if I'm using this library to fetch the colors from the Figma page and generate CSS variables based on it?

Are there plans to use the local variables from the page and export them as CSS/SCSS/etc? I'm still new to working with Figma API so I'm not aware of any limitations at the moment, but doing this would be a really cool solution for exporting colors and other variables.

**Comment by marcomontalbano** [comment]
Hi @Ingramz and @darktasevski, I just released the alpha `^4.8.0-alpha.0` that contains a fix to this issue.

You can use this new version by updating all the `@figma-export/*` dependencies to `^4.8.0-alpha.0`. Let me know.

------

@darktasevski could you open another issue with your latest question? I'll investigate about that.

**Comment by marcomontalbano** [comment]
Hi @Ingramz, I just released the [v4.8.0](https://github.com/marcomontalbano/figma-export/releases/tag/v4.8.0) that contains the fix to this issue.

**Comment by Ingramz** [comment]
Thank you for the fixes, unfortunately the project I meant to use this tool on is no longer being worked on, but I'll try digging up the old documents to test the fixes shortly.
