### ISSUE TITLE
Noob question :-(

### ISSUE THREAD

**Issue by sm1therz** [marcomontalbano/figma-export#149]
Hi there, 

Sorry if I'm asking a totally obvious question but, how do you use this? It looks really cool.

I made a personal access token, like the readme says. After that though, I'm kinda lost.

I get the feeling this is for people who know how to code. Right?

**Comment by marcomontalbano** [comment]
Hi @sm1therz, thanks a lot for your interest in this library!

Knowing how to code is not strictly required, but you should know how to use a shell/terminal, a bit of JavaScript (if you need to write the `.figmaexportrc` configuration file), and the tools around it.

There are some pre-requirements that I didn't mention in the readme, but I'll take the opportunity to write a proper section.

This is a JavaScript project, so you'll need to install Node.js to make it run. You can download it directly from the [official Node.js website](https://nodejs.org/). Node.js automatically comes with `npm` and `npx` commands that you can use in your Terminal.

At this point, you can continue reading from "[🧪 Just Try](https://github.com/marcomontalbano/figma-export#test_tube-just-try)" and everything should work properly.

Let me know if this helps you.

https://github.com/marcomontalbano/figma-export/assets/1681269/beff7758-c4d9-4da6-b894-15aa1f8950e6
