### ISSUE TITLE
Support latest node version

### ISSUE THREAD

**Issue by davazp** [marcomontalbano/figma-export#49]
Those packages specify the latest valid node version as <= 13.x.  Is this intentional? Anything that breaks with the latest 14.x release and I could help with?  or should this just be adjusted in the package.json?

```
error @figma-export/cli@2.0.0: The engine "node" is incompatible with this module. Expected version ">= 8.3 <= 13.x". Got "14.5.0"
```

**Comment by marcomontalbano** [comment]
Hi @davazp, yes that was intentional, but I'm going to test all packages on Node 14.x and I'll release a new version soon.
I'll keep you posted.

**Comment by marcomontalbano** [comment]
Hi, I added support to Node 14.x in `v2.2.0`.
Let me know! In the meantime, I'm closing the ticket.
