### ISSUE TITLE
Ability to export text/color styles from a Library

### ISSUE THREAD

**Issue by docmars** [marcomontalbano/figma-export#85]
Hi there! I might be misunderstanding what this tool is already capable of, but is there a way to export all colors / font styles from a Figma Library (not just files)?

If not, I'd like to request the feature here. Nice work on this!

**Comment by marcomontalbano** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Export `team-*` and `files-*`](https://trello.com/c/GVb3v7Xw/110-export-team-and-files)

**Comment by marcomontalbano** [comment]
Hi @docmars, thanks for your feedback!

Currently this tool is only leveraging on Figma files.
Even if you create a library, styles and components live in the files they are originally created in. So as a workaround you can still use this tool to export your team styles from that file.

Let me know if this is preventing you from using the tool.
