### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by berkaey** [marcomontalbano/figma-export#86]
Hi, looks like you restricted node version on your package.json, we want to use it under node v16. If this package works under 16 can you update the package.json.

**Comment by marcomontalbano** [comment]
Hi @berkaey, thanks for reporting this! I'll check on node 16 and update the package.json!

**Comment by marcomontalbano** [comment]
Hi @berkaey, I just released version 3.3.0 for all packages removing the limitation to nodejs version.
Let me know if now is working properly.

**Comment by berkaey** [comment]
Thanks, yes it works perfectly. 👍
