### ISSUE TITLE
Expose the component ID in the ComponentExtras

### ISSUE THREAD

**Issue by didoo** [marcomontalbano/figma-export#92]
Currently the function `getBasename` in the _output-components-as-svg_ module uses only the `basename` value to generate the file name in output:

https://github.com/marcomontalbano/figma-export/blob/9ac8278779265299e6101ce83717a9ee3b8b75a6/packages/output-components-as-svg/src/index.ts#L16

But if the icons are variants, there may be cases in which two different variants have the same name (because of how Figma assigns the name to the variants). For example, we have a set of icons as [component sets](https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-variants), where each one of them has two sizes, (each one is a component, with two variants, and a property with two values `sm` and `md` assigned to each one of them).

When we export the icons, even if the icons' (parent) component set have different names, the variants all have name `Size=sm` or `Size=md` so each icon exported overrides the previous one, and we end up with only two files (one called ``Size=sm.svg` and the other ``Size=md.svg`.

What I propose here is to expose also the ID of the component (which we know is unique) so that a consumer of the library can create their own unique basename and use the `getBasename` function (passed to the `outputComponentsAsSvg` outputter) to override the default behaviour, eg. 

```
getBasename: (options): string => `${options.id}__${options.basename}.svg`
```

The way in which we can expose it is to add an `id` key to `ComponentExtras` type, and then in the `getComponents` method add the `id` value to the `figmaExport` object.

I'll submit a PR for this small change.

**Comment by marcomontalbano** [comment]
Thanks a lot @didoo for the time you spent on this!
I'll push your changes on the next coming release v3.4.0

**Comment by didoo** [comment]
@marcomontalbano thanks! 🙏

**Comment by marcomontalbano** [comment]
Hi @didoo, v3.4.0 has been just released :tada:

Let me know if everything is working properly and thanks again!

**Comment by didoo** [comment]
@marcomontalbano yes, it works perfectly. Thanks again

**Comment by amcolash** [comment]
This is great. I have a very similar scenario, however for our assets sometimes there are multiple levels of information lost by compressing the components into a flat array. I found a simple approach to getting this additional information by modifying the base `getComponents` function call and appending additional information (in this case a parent path) onto the component. I am not sure if this _should_ be inside this additional metadata, but it sure is helpful for me and I assume others.

Note the additional parent parameter in the recursive function
```ts
const getComponents = (parent: string, children: readonly Node[] = []): any[] => {
  let components = [];

  children.forEach((component) => {
    if (component.type === 'COMPONENT') {
      components.push({
        parent,
        ...component,
      });

      return;
    }

    if ('children' in component) {
      components = [...components, ...getComponents(parent + '/' + component.name, component.children)];
    }
  });

  return components;
};
```

Which then will produce additional `parent` information for each component like: `parent: 'Document/Page 1/Icons/Analytics/Line'`.

Now how this information is used is up to the user, but I think it could be quite useful for my needs. If this doesn't fit inside the core of this project, I will continue by making a mapping of the `id -> parent` before the export and then generating a suitable name based off of that.

Thanks so much for the work on this project!

**Comment by didoo** [comment]
Personally I don't think we should add too much to the object, apart from the ID. And this is my thinking: with the ID, essentially you can do whatever you want, using the REST APIs. So there're no need to introduce other meta-data (everyone may have a different need, and in no time the metadata object would become uber-complex. 

My suggestion (and that's what I did on my side) is to use the REST APIs to build an object with all the metadata you need, and then when exporting the assets via Figma-Export use the specific metadata for that component ID for whatever is your need. You can see what I did here:
https://github.com/hashicorp/flight/blob/85ea7fc6f22ae675a6d4d54b71adef8454c27135/flight-icons/scripts/sync.ts#L47-L53

**Comment by amcolash** [comment]
Sure thing, makes sense. I did take that route and it is working beautifully - I do love the figma API! Thanks again for the module and appreciate your suggestions.
