### ISSUE TITLE
Export styles to JSON

### ISSUE THREAD

**Issue by kedano** [marcomontalbano/figma-export#95]
Hi, it would be great if it was possible to export the styles to a JSON file with an object-structure that follows the same kind of naming convention you have in your figma file.

Example style name in Figma:

Light theme / Primary / Main -> #ff0000
Dark theme / Primary / Main -> #00ff00

JSON output:

`{
  "Light theme":{
    "Primary":{
      "main": " #ff000"
    }
  },
  "Dark theme":{
    "Primary":{
      "main": " #00ff00"
    }
  }
}`

**Comment by marcomontalbano** [comment]
Hi @kedano, this is a very specific use-case.
All the `outputter`s are built to be used by a specific language or library.
I don't think there's a generic json structure that can be used by everybody.

Anyway you can create your own `outputter` and, if you like, you can share it with others inside the discussion tab.

This is an example that you can use as a starting point:

```ts
import { FigmaExportRC, StylesCommandOptions, StyleTypeFill } from '@figma-export/types';

import fs = require('fs');
import path = require('path');
import makeDir = require('make-dir');

const styleOptions: StylesCommandOptions = {
    fileId: 'fzYhvQpqwhZDUImRz431Qo',
    outputters: [
        async (styles) => {
            const jsonObject = styles
                .filter(style => style.visible && style.styleType === 'FILL')
                .reduce((acc, style) => {
                    const value = (style as StyleTypeFill).fills
                        .filter((fill) => fill.visible)
                        .map((fill) => fill.value)
                        .join(', ');

                    return {
                        ...acc,
                        [style.name]: value
                    }
                }, {})

            const output = './output/styles/json'
            const filePath = makeDir.sync(path.resolve(output));
            fs.writeFileSync(path.resolve(filePath, 'styles.json'), JSON.stringify(jsonObject, undefined, 4));
        }
    ]
};

(module.exports as FigmaExportRC) = {
    commands: [
        ['styles', styleOptions]
    ]
};
```
